FROM python:3.12-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Only install what is needed for api.py
RUN pip install --no-cache-dir \
    mlflow==3.1.1 \
    scikit-learn==1.7.0 \
    pandas==2.3.1 \
    fastapi==0.116.1 \
    uvicorn==0.35.0 \
    python-dotenv==1.0.1

# Copy project files
COPY src/api/app.py .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]