FROM python:3.12-slim

WORKDIR /app

# install minimal dependencies
RUN pip install --no-cache-dir \
    streamlit==1.35.0 \
    requests==2.31.0 \
    python-dotenv==1.0.1

# copy ui.py only
COPY gitui.py .

EXPOSE 8501
CMD ["streamlit", "run", "ui.py", "--server.address=0.0.0.0", "--server.port=8501"]
