version: "3.8"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-artifacts:/mlartifacts
    command: mlflow ui --host 0.0.0.0 --port 5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - backend
    ports:
      - "8501:8501"
