stages:
  preprocess:
    cmd: poetry run python src/preprocess.py data/raw/train.csv 
      data/processed/train_processed.csv
    deps:
    - data/raw/train.csv
    - src/preprocess.py
    outs:
    - data/processed/train_processed.csv
  train:
    cmd: poetry run python src/train2.py data/processed/train_processed.csv
    deps:
    - data/processed/train_processed.csv
    - src/train2.py
  evaluate:
    cmd: poetry run python src/evaluate.py data/processed/train_processed.csv
    deps:
    - data/processed/train_processed.csv
    - src/evaluate.py
