stages:

  prepare:
    cmd: python src/data/prepare.py
    deps:
      - data/train.csv
      - src/data/prepare.py
    outs:
      - data/prepared.csv

  train:
    cmd: python src/services/train.py
    deps:
      - src/services/train.py
      - params.yaml
      - data/prepared.csv
    params:
      - data.test_size
      - data.random_state
      - model.hyperparams
      - validation
    outs:
      - model.pkl
      - metrics.json
