stages:

  prepare:
    cmd: python prepare.py
    deps:
      - data/train.csv
      - prepare.py
    outs:
      - data/prepared.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - params.yaml
      - data/prepared.csv
    params:
      - data.test_size
      - data.random_state
      - model.hyperparams
      - validation
    outs:
      - model.pkl
      - metrics.json
