groups:
- name: service_alerts
  rules:
  - alert: FastAPIHighRequestLatency
    expr: http_request_duration_seconds_avg > 1
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "High request latency on FastAPI"
      description: "The average response time is >1s"
