channels:
- conda-forge
dependencies:
- python=3.10.2
- pip<=21.2.4
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.1
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env
