mlflow:
  tracking_uri: "http://mlflow:5000" # Replace with your MLflow server URI
  experiment_name: "regression_experiment"
  model_name: "regression_model"

data:
  test_size: 0.2
  random_state: 42

model:
  hyperparams:
    n_estimators: 100
    max_depth: 5
    random_state: 42
