name: CI Pipeline

# This workflow is triggered on a push to the main branch or a pull request.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # --- Python Environment Setup ---
      # Sets up Python and installs Poetry for dependency management.
      - name: Setup Python with Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install Poetry dependencies
        run: poetry install
      
      # --- Linting & Formatting ---
      # Runs Black and Flake8 to enforce code style and catch simple errors.
      - name: Run Black formatter check
        run: poetry run black --check .
        continue-on-error: true

      - name: Run Flake8 linter
        run: poetry run flake8 . --max-line-length=127
        continue-on-error: true
        
      # --- Unit Testing ---
      # Executes all unit tests located in the './tests/unit' directory.
      - name: Run unit tests with Pytest
        run: poetry run pytest ./tests/unit
