name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup DVC
      uses: iterative/setup-dvc@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: pytest

    # - name: Lint with Flake8
    #   run: |
    #     flake8 . --count --max-line-length=127

    - name: Check cache consistency
      run: dvc status -c
      
    - name: Start MLflow Tracking Server
      run: |
        mlflow server \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlruns \
          --host 0.0.0.0 \
          --port 5000 &
        # wait for server to start
        sleep 5

    - name: Reproduce with pull
      run: dvc repro --pull --force
