name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup DVC
      uses: iterative/setup-dvc@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Lint with Flake8
    #   run: |
    #     flake8 . --count --max-line-length=127

    - name: Check cache consistency
      run: dvc status -c
      
    - name: Start MLflow Tracking Server
      run: |
        mlflow server \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlruns \
          --host 127.0.0.1 \
          --port 5000 &
        # wait for server to start
        sleep 5

    - name: Reproduce with pull
      run: dvc repro --pull

    # - name: Run tests
    #   run: pytest
  
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup Python & install dependencies
        run: |
          pip install -r requirements.txt requests uvicorn streamlit pytest
  
      - name: Start FastAPI server
        run: |
          uvicorn app:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid
          sleep 5
  
      - name: Start Streamlit UI
        run: |
          python -m streamlit run ui.py --server.headless true --server.port 8501 &
          echo $! > streamlit.pid
          sleep 5
  
      - name: Teardown servers
        run: |
          kill $(cat uvicorn.pid) || true
          kill $(cat streamlit.pid) || true
  